version: "3"
services:
  reverseproxy:
    build:
      context: .
      image: your_dockerhub_username_lowercase/reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
      image: your_dockerhub_username_lowercase/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed
      image: your_dockerhub_username_lowercase/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend
      image: your_dockerhub_username_lowercase/udacity-frontend:local
