branch-defaults:
  default:
    environment: udagram-madejczyk-dev-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udagram-madejczyk-dev
  branch: null
  default_ec2_keyname: udagram-madejczyk
  default_platform: Node.js
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
